name: Build and Test

on: [push]

jobs:
    build:
        runs-on: ${{ matrix.operating-system }}

        strategy:
            matrix:
                # TODO get tests working in Windows
                # windows-latest
                operating-system: [ubuntu-latest, macos-latest]

        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js latest
              uses: actions/setup-node@v3
              with:
                  node-version: latest
            - name: install
              run: |
                  npm i
            - name: check formatting
              run: |
                  npm run prettier:check
            - name: build
              run: |
                  npm run clean
                  npm run build
            - name: test
              run: |
                  npm test
            - name: check repo is clean
              # skip this check in windows for now, as the build outputs may get slightly modified in Windows, which we want to fix.
              if: runner.os != 'Windows'
              run: |
                  git add . && git diff --quiet && git diff --cached --quiet
              env:
                  CI: true
