name: Build and Test

on: [push]

jobs:
    build:
        runs-on: ${{ matrix.operating-system }}

        strategy:
            matrix:
                node-version: [14.x]
                # TODO get tests working in Windows
                # windows-latest
                operating-system: [ubuntu-latest, macos-latest]

        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: npm install, build, and test
              run: |
                  npm i
                  npm test
              env:
                  CI: true
